-- Linux commands:
-- psql -U postgres -f /home/tallyList.sql 
-- 
--Database : tallyList
SET SESSION AUTHORIZATION 'postgres';
SET search_path = public, pg_catalog;
-- Structure for table usr (OID = 24639):
CREATE TABLE usr (
    id integer NOT NULL,
    name varchar(30)
) WITHOUT OIDS;
-- Structure for table order (OID = 24642):
CREATE TABLE "order" (
    id integer NOT NULL,
    user_id integer,
    product_id integer,
    quantity integer
) WITHOUT OIDS;
-- Structure for table product (OID = 24645):
CREATE TABLE product (
    id integer NOT NULL,
    name varchar(30),
    price real,
    icon varchar(30) DEFAULT NULL::character varying
) WITHOUT OIDS;
-- Structure for table sys_user (OID = 24649):
CREATE TABLE sys_user (
    id integer NOT NULL,
    name varchar(30),
    pwd_hash varchar(150)
) WITHOUT OIDS;
--
-- Data for blobs (OID = 24639) (LIMIT 0,3)
--
INSERT INTO usr (id, name) VALUES (10, 'User 1');
INSERT INTO usr (id, name) VALUES (11, 'User 2');
INSERT INTO usr (id, name) VALUES (12, 'User 3');
COMMIT;
--
-- Data for blobs (OID = 24645) (LIMIT 0,4)
--
INSERT INTO product (id, name, price, icon) VALUES (11, 'Beer', 1.5, 'beer');
INSERT INTO product (id, name, price, icon) VALUES (13, 'Shot', 0.5, 'bullseye');
INSERT INTO product (id, name, price, icon) VALUES (10, 'Non Alcoholic', 1, 'tint');
INSERT INTO product (id, name, price, icon) VALUES (12, 'Drink', 2, 'cocktail');
COMMIT;
--
INSERT INTO sys_user (id, name, pwd_hash) VALUES (12, 'admin', '$2b$10$FIUM4uAgTWpu5OTeo0FRVOp7cMZn9L3wV00B9MwK9x0xfS3euhWqe');
COMMIT;
--
ALTER TABLE public.usr
    ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH 20);
--
ALTER TABLE public.product
    ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH 20);
--
ALTER TABLE public."order"
    ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH 20);
--
ALTER TABLE public.sys_user
    ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH 20);
--
-- Definition for index usr_pkey (OID = 24652):
ALTER TABLE ONLY usr
    ADD CONSTRAINT usr_pkey PRIMARY KEY (id);
-- Definition for index order_pkey (OID = 24654):
ALTER TABLE ONLY "order"
    ADD CONSTRAINT order_pkey PRIMARY KEY (id);
-- Definition for index product_pkey (OID = 24656):
ALTER TABLE ONLY product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);
-- Definition for index sys_user_pkey (OID = 24658):
ALTER TABLE ONLY sys_user
    ADD CONSTRAINT sys_user_pkey PRIMARY KEY (id);
-- Definition for index foreign_key01_user_id (OID = 24660):
ALTER TABLE ONLY "order"
    ADD CONSTRAINT foreign_key01_user_id FOREIGN KEY (user_id) REFERENCES usr(id) ON DELETE CASCADE;
-- Definition for index foreign_key01_prod_id (OID = 24665):
ALTER TABLE ONLY "order"
    ADD CONSTRAINT foreign_key01_prod_id FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
SET search_path = pg_catalog, pg_catalog;
COMMENT ON SCHEMA public IS 'standard public schema';

