FROM node:10-alpine

RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python
RUN npm install --quiet node-gyp -g

WORKDIR /app

COPY package.json /app
RUN npm install --production
COPY . /app

# production
CMD node index.js




